index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('calculate/', views.calculate, name='calculate'),
]

webcalculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

index/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import requests
from rest_framework import status


# Create your views here.
def index(request):
    return render(request, 'index.html')

def calculate(request):
    if request.method == "POST":
        num1 = request.POST['num1']
        num2 = request.POST['num2']

        # test using api.mathjs
        # url = 'http://api.mathjs.org/v4/?expr=' + num1 + '%2B' + num2
        # response = requests.get(url)
        # answer = response.content.decode("utf-8")
        # return HttpResponseRedirect('')

        data = {
            'num1' : num1,
            'num2' : num2,
        }
        # url = 'http://127.0.0.1:8000/addition/'
        url = 'https://restapi-cal.herokuapp.com/addition/'
        response = requests.get(url, data=data)
        if response.content.decode("utf-8") == "{}":
            answer = "Error : Please fill the number on all fields"
        else:
            answer = response.content.decode("utf-8")

    else:
        answer = 0
    return render(request, 'result.html', {"answer":answer})

index/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'nama_file.css' %}"> -->
    <title>Web Calculator</title>
</head>
<body>
    <div style="text-align: center;">
        <img src="{% static 'calculator.png' %}" alt="calculator" height="10%" width="10%">
        <br>
        <h2>Additions</h2>
        <form action="/calculate/" method="post">
            {% csrf_token %}
            <label for="num1">First number :</label><br>
            <input type="number" id="num1" name="num1" style="width: 50px;" value="0"><br>
            <label for="num2">Second number :</label><br>
            <input type="number" id="num2" name="num2" style="width: 50px;" value="0">
            <br><br>
            <input type="submit" value="Add">
          </form>
          <br>
          <!-- <h3>Answer = </h3> -->
    </div>
    
</body>
</html>

index/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
</head>
<body style="text-align: center;">
    <h2>The Answer is :</h2>
    <h3 style="font-size: 50px;">{{answer}}</h3>
    <br>
    <br>
    <a href="{% url 'index:index' %}">go back</a>
</body>
</html>